# Generated by Django 4.2.6 on 2023-11-12 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='identitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_identitas', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Biodata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npm', models.CharField(max_length=100)),
                ('jurusan', models.TextField(max_length=100)),
                ('identitas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikasi.identitas')),
            ],
        ),
    ]
